import { useCallback, useState } from "react";
import { useApp } from "./context";
import { useFrameStore } from "./hooks";
import type { PracticeScores } from "../practice/types";

const scoreRows:[keyof PracticeScores,string][]=[["beatMatching","Beat Matching"],["timing","Timing"],["transition","Transition"],["eqBalance","EQ Balance"],["phraseAlignment","Phrase Alignment"],["harmonicCompatibility","Harmonic Compatibility"],["gainControl","Gain Control"],["trackSelection","Track Selection"]];
const time=(s:number)=>`${Math.floor(s/60).toString().padStart(2,"0")}:${Math.round(s%60).toString().padStart(2,"0")}`;
export function PracticePanel(){
  const app=useApp(),p=app.practice;
  const state=useFrameStore(useCallback(cb=>p.on("change",cb),[p]),()=>p.getState());
  const playlists=useFrameStore(useCallback(cb=>app.playlists.on("change",cb),[app.playlists]),()=>app.playlists.getState());
  const [history,setHistory]=useState(false),r=state.result;
  const avg=state.history.length?Math.round(state.history.reduce((n,x)=>n+x.scores.overall,0)/state.history.length):0,best=Math.max(0,...state.history.map(x=>x.scores.overall));
  if(history)return <div className="practice"><div className="toolbar"><b>PRACTICE HISTORY</b><button onClick={()=>setHistory(false)}>Back to Practice</button><span>Average Score: <b>{avg}%</b></span><span>Personal Best: <b>{best}%</b></span></div><div className="table-wrap"><table className="tracks"><thead><tr><th>Date</th><th>Track A</th><th>Track B</th><th>Overall</th><th>Beat Matching</th><th>Timing</th><th>Transition</th><th>EQ Balance</th></tr></thead><tbody>{[...state.history].reverse().map(x=><tr key={x.id}><td>{new Date(x.date).toLocaleString()}</td><td>{x.trackATitle}</td><td>{x.trackBTitle}</td><td><b>{x.scores.overall}%</b></td><td>{x.scores.beatMatching}%</td><td>{x.scores.timing}%</td><td>{x.scores.transition}%</td><td>{x.scores.eqBalance}%</td></tr>)}</tbody></table></div></div>;
  if(state.status==="intro")return <div className="practice intro"><h2>DJ PRACTICE MODE</h2><p>Test your mixing skills. We'll give you a random track. Choose another track and mix it in. When you're finished, we'll analyse your mix and show you where you nailed it and where you can improve.</p><div className="practice-options"><label>Difficulty <select value={state.difficulty} onChange={e=>p.setDifficulty(e.target.value as typeof state.difficulty)}><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option><option value="custom">Custom</option></select></label><label>Practice from playlist <select value={state.playlistId??""} onChange={e=>p.setPlaylist(e.target.value||null)}><option value="">All local tracks</option>{playlists.playlists.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div>{state.difficulty==="custom"&&<div className="practice-assists">{([['showBpm','Display BPM'],['showKey','Display key'],['showBeatgrid','Display beatgrid'],['allowSync','Allow Sync']] as const).map(([k,l])=><label key={k}><input type="checkbox" checked={state.assists[k]} onChange={e=>p.setAssists({[k]:e.target.checked})}/>{l}</label>)}</div>}<div className="toolbar"><button className="primary" onClick={()=>void p.start()}>START PRACTICE</button><button onClick={()=>setHistory(true)}>PRACTICE HISTORY ({state.history.length})</button></div></div>;
  if(r)return <div className="practice results"><div className="toolbar"><b>PRACTICE RESULTS</b><span>{r.trackATitle} <b>mixed into</b> {r.trackBTitle}</span><button onClick={()=>void p.retry()}>TRY AGAIN</button><button className="primary" onClick={()=>void p.newChallenge()}>NEW CHALLENGE</button><button onClick={()=>setHistory(true)}>PRACTICE HISTORY</button></div><div className="practice-score-overall">Overall Score <strong>{r.scores.overall}%</strong></div><div className="practice-scores">{scoreRows.map(([k,l])=><div key={k}><span>{l}</span><meter min="0" max="100" value={r.scores[k]}/><b>{r.scores[k]}%</b></div>)}</div><div className="practice-coach"><section><h3>What went well</h3>{r.strengths.map((x,i)=><p key={i}>✓ {x}</p>)}</section><section><h3>What to improve</h3>{r.improvements.map((x,i)=><p key={i}>△ {x}</p>)}</section></div><h3>Performance timeline</h3><div className="practice-timeline">{r.events.map((e,i)=><button key={i} style={{left:`${Math.min(96,e.at/Math.max(1,r.events.at(-1)?.at??1)*96)}%`}} title={e.detail} onClick={()=>p.replay(e.at)}><i/>{time(e.at)}<span>{e.label}</span></button>)}</div></div>;
  return <div className="practice active"><div className="toolbar"><b>DJ PRACTICE MODE · {state.status==="transition"?"TRANSITION DETECTED":"IN PROGRESS"}</b><button onClick={()=>p.finish()} disabled={!state.trackB}>FINISH MIX</button><button onClick={()=>void p.newChallenge()}>New Challenge</button></div><div className="practice-instruction"><div><small>STARTING TRACK · DECK A</small><strong>{state.trackA?.artist} — {state.trackA?.title}</strong></div><span>→</span><div><small>YOUR SELECTION · DECK B</small><strong>{state.trackB?`${state.trackB.artist} — ${state.trackB.title}`:"Choose a suitable library track and load it onto Deck B"}</strong></div></div><p className="hint">Use the normal decks, mixer, STEMS, EQ, filters, loops and effects. Practice Mode observes without controlling your transition.{!state.assists.allowSync&&" Sync is disabled for this challenge."}</p></div>;
}
