import { Emitter } from "../core/events";
import type { DJEngine, EngineState } from "../core/engine/DJEngine";
import type { CommandBus } from "../core/commands";
import type { TrackInfo, AudioEngine } from "../core/engine/types";
import type { LibraryStore } from "../library/LibraryStore";
import type { PlaylistStore } from "../library/PlaylistStore";
import type { PreparationStore } from "../preparation/PreparationStore";
import { scorePractice } from "./scoring";
import type { PracticeAssists, PracticeDifficulty, PracticeEvent, PracticeResult, PracticeSample } from "./types";

export type PracticeStatus="intro"|"running"|"transition"|"results";
export interface PracticeState { status:PracticeStatus; difficulty:PracticeDifficulty; assists:PracticeAssists; playlistId:string|null; trackA:TrackInfo|null; trackB:TrackInfo|null; startedAt:number; events:PracticeEvent[]; result:PracticeResult|null; history:PracticeResult[] }
const presets:Record<Exclude<PracticeDifficulty,"custom">,PracticeAssists>={beginner:{showBpm:true,showKey:true,showBeatgrid:true,allowSync:true},intermediate:{showBpm:true,showKey:true,showBeatgrid:true,allowSync:true},advanced:{showBpm:false,showKey:false,showBeatgrid:false,allowSync:false}};
const HISTORY="dbdj.practice.history.v1";
export class PracticeService extends Emitter<{change:PracticeState}> {
  private state:PracticeState={status:"intro",difficulty:"beginner",assists:{...presets.beginner},playlistId:null,trackA:null,trackB:null,startedAt:0,events:[],result:null,history:this.loadHistory()};
  private samples:PracticeSample[]=[]; private last:EngineState|null=null; private lastTick=0; private silentASince=0;
  constructor(private o:{engine:DJEngine;bus:CommandBus;audio:AudioEngine;library:LibraryStore;playlists:PlaylistStore;preparation:PreparationStore}){super();o.engine.on("state",s=>this.observe(s));}
  getState(){return this.state} private set(p:Partial<PracticeState>){this.state={...this.state,...p};this.applyAssists();this.emit("change",this.state)}
  private loadHistory():PracticeResult[]{try{return JSON.parse(localStorage.getItem(HISTORY)||"[]")}catch{return[]}}
  private saveHistory(rows:PracticeResult[]){try{localStorage.setItem(HISTORY,JSON.stringify(rows.slice(-100)))}catch{}}
  setDifficulty(difficulty:PracticeDifficulty){this.set({difficulty,assists:difficulty==="custom"?this.state.assists:{...presets[difficulty]}})}
  setAssists(assists:Partial<PracticeAssists>){this.set({difficulty:"custom",assists:{...this.state.assists,...assists}})}
  setPlaylist(id:string|null){this.set({playlistId:id})}
  private candidates(){const all=this.o.library.getState().tracks.filter(t=>t.source==="local"&&!t.unavailableReason);const p=this.state.playlistId&&this.o.playlists.get(this.state.playlistId);return p? p.refs.map(r=>this.o.library.getByRef(r)).filter((t):t is TrackInfo=>!!t&&!t.unavailableReason):all}
  async start(track?:TrackInfo){const rows=this.candidates();const a=track??rows[Math.floor(Math.random()*rows.length)];if(!a)return false;for(let d=0;d<2;d++)if(this.o.engine.getState().decks[d].playing)this.o.bus.send(`deck${d+1}.play`,1,"system");await this.o.engine.loadTrack(0,a,"manual");this.o.engine.seekTo(0,0);this.samples=[];this.last=null;this.silentASince=0;this.set({status:"running",trackA:a,trackB:null,startedAt:performance.now(),events:[{at:0,kind:"start",label:"Challenge started"}],result:null});this.o.bus.send("deck1.play",1,"system");return true}
  async retry(){if(!this.state.trackA||!this.state.trackB)return;const b=this.state.trackB;await this.start(this.state.trackA);await this.o.engine.loadTrack(1,b,"manual")}
  newChallenge(){return this.start()}
  finish(){const a=this.state.trackA,b=this.state.trackB;if(!a||!b||!this.samples.length)return;const result=scorePractice(a,b,this.o.preparation.forRef(a.ref),this.o.preparation.forRef(b.ref),this.samples,this.state.events);const history=[...this.state.history,result];this.saveHistory(history);this.set({status:"results",result,history})}
  replay(at:number){const s=this.samples.reduce((best,x)=>Math.abs(x.at-at)<Math.abs(best.at-at)?x:best,this.samples[0]);if(!s)return;this.o.engine.seekTo(0,Math.max(0,s.posA-2));this.o.engine.seekTo(1,Math.max(0,s.posB-2))}
  tick(){if(!["running","transition"].includes(this.state.status)||performance.now()-this.lastTick<100)return;this.lastTick=performance.now();const s=this.o.engine.getState(),a=s.decks[0],b=s.decks[1];if(!this.state.trackB&&b.status==="ready"&&b.track)this.set({trackB:b.track});if(!b.track)return;const at=(performance.now()-this.state.startedAt)/1000,ba=this.o.engine.getBpm(0),bb=this.o.engine.getBpm(1),phase=this.phaseMs(a,b),levels=this.o.audio.getLevels(),ca=s.mixer.channels[0],cb=s.mixer.channels[1],x=s.mixer.crossfader;const sample:PracticeSample={at,posA:this.o.engine.getPosition(0),posB:this.o.engine.getPosition(1),bpmA:ba,bpmB:bb,phaseMs:phase,volumeA:a.playing?ca.volume*Math.min(1,(1-x)*2):0,volumeB:b.playing?cb.volume*Math.min(1,x*2):0,crossfader:x,eqLowA:ca.eqLow,eqLowB:cb.eqLow,filterA:ca.filter,filterB:cb.filter,clipping:levels.master>.98};const prev=this.samples.at(-1);this.samples.push(sample);if(prev&&phase!=null&&prev.phaseMs!=null){if(Math.abs(phase)>80&&Math.abs(prev.phaseMs)<=80)this.event("drift","Beat drift detected",`Track B moved ${Math.round(Math.abs(phase))} ms out of phase`);if(Math.abs(phase)<40&&Math.abs(prev.phaseMs)>=80)this.event("correction","Good beat correction",`Phase error reduced to ${Math.round(Math.abs(phase))} ms`)}if(this.state.status==="running"&&sample.volumeB>.08){this.event("transition","Track B introduced",phase==null?undefined:`Beat phase difference ${Math.round(Math.abs(phase))} ms`);this.set({status:"transition"})}if(this.state.status==="transition"){if(sample.volumeA<.04&&sample.volumeB>.08){if(!this.silentASince)this.silentASince=performance.now();else if(performance.now()-this.silentASince>2000){this.event("complete","Track A removed");this.finish()}}else this.silentASince=0}}
  private phaseMs(a:EngineState["decks"][number],b:EngineState["decks"][number]){if(!a.beatGrid||!b.beatGrid)return null;const pa=(this.o.engine.getPosition(0)-a.beatGrid.firstBeat)/(60/a.beatGrid.bpm),pb=(this.o.engine.getPosition(1)-b.beatGrid.firstBeat)/(60/b.beatGrid.bpm),delta=((pb-pa+.5)%1+1)%1-.5;return delta*60/(this.o.engine.getBpm(0)??a.beatGrid.bpm)*1000}
  private event(kind:string,label:string,detail?:string){this.set({events:[...this.state.events,{at:(performance.now()-this.state.startedAt)/1000,kind,label,detail}]})}
  private observe(s:EngineState){if(!["running","transition"].includes(this.state.status)){this.last=s;return}const p=this.last;if(p){const at=(performance.now()-this.state.startedAt)/1000,events=[...this.state.events];const add=(kind:string,label:string)=>events.push({at,kind,label});for(let i=0;i<2;i++){const a=p.mixer.channels[i],b=s.mixer.channels[i];if(Math.abs(a.eqLow-b.eqLow)>.12)add("eq",`Deck ${i?"B":"A"} bass EQ changed`);if(Math.abs(a.filter-b.filter)>.15)add("filter",`Deck ${i?"B":"A"} filter changed`);if(!p.decks[i].loop?.active&&s.decks[i].loop?.active)add("loop",`Deck ${i?"B":"A"} loop enabled`);if(p.fx.some((u,k)=>u.slots.some((x,j)=>!x.on&&s.fx[k]?.slots[j]?.on)))add("fx","Effect enabled")}if(Math.abs(p.mixer.crossfader-s.mixer.crossfader)>.15)add("crossfade","Crossfader moved");if(events.length!==this.state.events.length)this.set({events})}if(!this.state.assists.allowSync)for(let i=0;i<2;i++)if(s.decks[i].sync)this.o.bus.send(`deck${i+1}.sync`,1,"system");this.last=s}
  private applyAssists(){document.documentElement.classList.toggle("practice-hide-bpm",this.state.status!=="intro"&&!this.state.assists.showBpm);document.documentElement.classList.toggle("practice-hide-key",this.state.status!=="intro"&&!this.state.assists.showKey);document.documentElement.classList.toggle("practice-hide-grid",this.state.status!=="intro"&&!this.state.assists.showBeatgrid)}
}
