/**
 * User-facing capability catalogue rendered by the About screen.
 * Architecture rule: every product feature change must update this catalogue
 * in the same change set. See docs/ARCHITECTURE.md, "Feature catalogue".
 */
export interface FeatureGroup { title:string; icon:string; features:string[] }
export const DEVELOPED_FEATURES:FeatureGroup[]=[
  {title:"Decks & playback",icon:"▶",features:["Two independent low-latency decks","Play/pause, CDJ cue and hold-to-preview","Tempo ranges, pitch control, key lock and vinyl scratching","Jog nudging, beat Sync and tempo master","Eight saved hot cues, saved loops and beat loops","Real track waveforms, high-contrast tempo-aware beatgrids and phrase/cue markers"]},
  {title:"Mixer & effects",icon:"🎚",features:["Gain, three-band EQ and frequency kills","Per-deck filters, channel faders and crossfader curves","Master and headphone cue/mix routing","Level metering and clipping visibility","Dual multi-effect units with beat-synced timing and deck/STEM assignment"]},
  {title:"STEMS & mashups",icon:"⚡",features:["Local four-stem separation: vocals, drums, bass and instruments","Per-stem mute, solo, volume, waveforms and FX routing","Mashup compatibility recommendations","Live Mashup editor with phrase blocks and source swapping","Full-length MP3 mashup rendering","Auto Mashup and Manual Mashup project libraries","Save live deck, mixer, filter, STEM and FX setups as Manual Mashups","Load saved mashups directly to both decks"]},
  {title:"Library & preparation",icon:"▦",features:["Persistent local music library and tag reading","Search, sorting, ratings and combined advanced filters","Persistent playlists with ordering, duplication and multi-select actions","Background BPM, key, Camelot, energy, beatgrid, phrase and cue analysis","Recommended Mix In/Mix Out points and waveform markers","Track compatibility scoring using tempo, harmony, energy, genre and structure"]},
  {title:"Auto DJ & discovery",icon:"↝",features:["Editable Auto DJ queue integrated with playlists","Fade, Beat Mix and Smart transition styles","Selectable transition duration and phrase alignment","Beat matching, BPM Sync and key-aware ordering","Visible transition countdown, markers and transition regions","DJMix playlist generation with energy-flow preferences","Mashup and compatible-track discovery with explained match scores"]},
  {title:"Practice & coaching",icon:"◆",features:["Random challenges from the library or a chosen playlist","Beginner, Intermediate, Advanced and Custom assists","Optional explained match suggestions with a disclosed score penalty","Live observation of beat phase, timing, faders, EQ, filters and effects","Deterministic Beat Matching, Timing, Transition and EQ Balance scores","Phrase, harmony, gain and track-selection analysis","Measured coaching feedback and clickable performance timeline","Persistent practice history, averages, personal bests and retries"]},
  {title:"Controllers & interface",icon:"🎛",features:["Pioneer DDJ-SB auto-detection, mapping and LED feedback","DDJ-SB sound-card routing guidance for its hardware Master and Headphone level controls","Hot-plug resilience, controller test, event feed and MIDI monitor","Mixxx MIDI mapping import and mapping export","Keyboard control for decks, browsing, hot cues and STEMS","Horizontal, Vertical and Classic responsive layouts","Header navigation, sidebar navigation and tiled feature landing pages"]},
  {title:"Streaming & matching",icon:"◉",features:["Spotify and Apple Music connection, metadata and playlist browsing","Smart Match to owned local recordings","Playable Audius discovery and deck loading","ISRC and metadata confidence matching with user confirmation","Provider diagnostics, retry handling and metadata caching"]},
  {title:"Desktop & reliability",icon:"▣",features:["Windows and macOS Electron application builds","Web Audio/AudioWorklet playback architecture","Persistent analysis, waveform, playlist, mashup and settings data","Audio device, routing, latency and sample-rate configuration","Diagnostics, event logging and background analysis without blocking playback"]},
];
export const COMING_SOON:FeatureGroup[]=[
  {title:"Transition intelligence",icon:"↝",features:["Exact mix instructions such as outgoing timestamp, incoming timestamp and bar length","Deeper transition-technique recommendations and rehearsal"]},
  {title:"DJ training curriculum",icon:"◇",features:["Guided Manual Beatmatch, Bass Swap, Phrase Mixing and Harmonic Mixing challenges","Long Blend, Quick Cut and Effects Transition lessons with tracked progression"]},
  {title:"Expanded performance tools",icon:"＋",features:["Set recording and session export","MIDI learn and a visual controller-mapping editor","Additional controllers, four-deck workflows and more advanced effects","Smart playlists driven by analysis and preparation rules"]},
];
